import Navbar from "../components/Navbar";


export const metadata = {
  title: "U Help | Dash",
  description: "Generated by create next app",
};

export default function DashboardLayout({children}) {
  return (
    <>
    <Navbar />
    {children}
    </>
  )
}
